---
version: "3"

services:
  mariadb:
    image: mariadb:10.1.22
    volumes:
      - maria-data:/var/lib/mysql
    networks:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: user
      MYSQL_PASSWORD: user
  mongodb:
    image: mongo:3.0.14
    volumes:
      - mongodb-data:/data/db
    networks:
      - database
  engine:
    image: tinkerwareio/engine
    networks:
      - database
    environment:
      DB_USER: "engine"
      DB_PASSWORD: "engine"
      DB_HOST: mongodb
  users:
    image: tinkerwareio/users
    ports:
      - "4000:4000"
    networks:
      - database
    environment:
      DB_HOST: mariadb
networks:
  database:
volumes:
  maria-data:
  mongodb-data:
